In [1]:
>>> from sklearn.model_selection import cross_val_score
>>> from sklearn.datasets import make_blobs
>>> from sklearn.ensemble import RandomForestClassifier
>>> from sklearn.ensemble import ExtraTreesClassifier
>>> from sklearn.tree import DecisionTreeClassifier

In [2]:
X, y = make_blobs(n_samples=10000, n_features=10, centers=100,random_state=0)

In [6]:
X

array([[  6.46907649,   4.25070317,  -8.63694437, ...,  -0.48172814,
         -6.44996141,  -2.65984972],
       [  6.48856404,   9.37957037,  10.32791736, ...,   3.37542134,
          7.41273719,  -9.72284371],
       [  8.37392753, -10.14342267,  -3.52753613, ...,  -7.31536045,
         -2.33070872,   6.44087163],
       ...,
       [  7.86551596,   6.19525794,   4.773955  , ...,   4.93452091,
         -4.52137856,   6.28178851],
       [-10.41156442,   1.40054826,  -1.97349572, ...,  -3.18210433,
          7.59487579,   4.62753678],
       [  7.40908901,  -7.3908382 ,  10.78350645, ...,  -3.26219501,
          5.73727272,  -4.97354916]])

In [5]:
y

array([85, 64, 93, ..., 98, 80, 91])

In [7]:
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)

In [8]:
scores = cross_val_score(clf, X, y)
scores

array([0.97852941, 0.98212121, 0.97757576])

In [9]:
clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [10]:
scores = cross_val_score(clf, X, y)
scores

array([0.97852941, 0.98212121, 0.97757576])

In [14]:
import scipy.stats as st
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

In [15]:
estimator = XGBClassifier(nthreads=-1)
params = {  
            "n_estimators": st.randint(3, 40),
            "max_depth": st.randint(3, 40),
            "learning_rate": st.uniform(0.05, 0.4),
            "colsample_bytree": st.beta(, 1),
            "subsample": st.beta(10, 1),
            "gamma": st.uniform(0, 10),
            'objective': ['binary:logistic'],
            'scale_pos_weight': st.randint(0, 2),
            "min_child_weight": st.expon(0, 50),
        }

# Random Search Training with 5 folds Cross Validation
clf = RandomizedSearchCV(estimator, params, cv=5,
                         n_jobs=1, n_iter=2) 

In [16]:
clf.fit(X, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `arra

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, nthreads=-1, objective='binary:logistic',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1),
          fit_params=None, iid=True, n_iter=2, n_jobs=1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA441AC8>, 'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA441C18>, 'learning_rate': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA441D68>, 'cols...F8>, 'min_child_weight': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA440BA8>},
          pre_dispatch='2*n_jobs', random_state=None, refit=

In [17]:
scores = clf.score(X, y)
scores

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9906

In [18]:
clf.predict(X)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([85, 64, 93, ..., 98, 80, 91])

In [20]:
y

array([85, 64, 93, ..., 98, 80, 91])

In [23]:
clf2 = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)
clf2.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [24]:
clf2.score(X, y)

1.0

In [27]:
vote.score(X, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [31]:
yy = vote.predict(X)
yy

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([85, 64, 93, ..., 98, 80, 91])

In [29]:
X

array([[  6.46907649,   4.25070317,  -8.63694437, ...,  -0.48172814,
         -6.44996141,  -2.65984972],
       [  6.48856404,   9.37957037,  10.32791736, ...,   3.37542134,
          7.41273719,  -9.72284371],
       [  8.37392753, -10.14342267,  -3.52753613, ...,  -7.31536045,
         -2.33070872,   6.44087163],
       ...,
       [  7.86551596,   6.19525794,   4.773955  , ...,   4.93452091,
         -4.52137856,   6.28178851],
       [-10.41156442,   1.40054826,  -1.97349572, ...,  -3.18210433,
          7.59487579,   4.62753678],
       [  7.40908901,  -7.3908382 ,  10.78350645, ...,  -3.26219501,
          5.73727272,  -4.97354916]])

In [30]:
import numpy as np

In [38]:
test = np.concatenate((yy, yy), axis=1)
test

AxisError: axis 1 is out of bounds for array of dimension 1

In [37]:
test.shape

(20000,)

In [53]:
test2 = np.reshape(yy, (yy.shape[0],1))

In [50]:
yy.shape

(10000,)

In [47]:
xx=X

In [49]:
xx.shape

(10000, 10)

In [54]:
test2 = np.reshape(yy, (yy.shape[0],1))
np.concatenate((xx, test2), axis=1)

array([[  6.46907649,   4.25070317,  -8.63694437, ...,  -6.44996141,
         -2.65984972,  85.        ],
       [  6.48856404,   9.37957037,  10.32791736, ...,   7.41273719,
         -9.72284371,  64.        ],
       [  8.37392753, -10.14342267,  -3.52753613, ...,  -2.33070872,
          6.44087163,  93.        ],
       ...,
       [  7.86551596,   6.19525794,   4.773955  , ...,  -4.52137856,
          6.28178851,  98.        ],
       [-10.41156442,   1.40054826,  -1.97349572, ...,   7.59487579,
          4.62753678,  80.        ],
       [  7.40908901,  -7.3908382 ,  10.78350645, ...,   5.73727272,
         -4.97354916,  91.        ]])

In [237]:
data

Normalised_AccAge  Normalised_Ad_amount  Normalised_AgeAtOpenAcc  \
0               0.265306              0.000000                 0.475728   
1               0.489796              0.333333                 0.621359   
2               0.408163              0.000000                 0.650485   
3               0.591837              0.000000                 0.233010   
4               0.387755              0.000000                 0.592233   
5               0.591837              0.000000                 0.640777   
6               0.693878              0.000000                 0.330097   
7               0.714286              0.000000                 0.524272   
8               0.306122              0.000000                 0.504854   
9               0.306122              0.000000                 0.368932   
10              0.306122              0.000000                 0.699029   
11              0.326531              0.000000                 0.563107   
12              0.653061              0.333333                 0.417476   
13              0.571429              0.000000                 0.427184   
14              0.489796              0.000000                 0.699029   
15              0.530612              0.000000                 0.563107   
16              0.551020              0.000000                 0.485437   
17              0.693878              0.000000                 0.446602   
18              0.612245              0.000000                 0.359223   
19              0.591837              0.333333                 0.514563   
20              0.530612              0.000000                 0.495146   
21              0.469388              0.333333                 0.601942   
22              0.653061              0.333333                 0.582524   
23              0.612245              0.000000                 0.368932   
24              0.448980              0.000000                 0.553398   
25              0.530612              0.000000                 0.524272   
26              0.428571              0.000000                 0.524272   
27              0.673469              0.000000                 0.514563   
28              0.510204              0.000000                 0.475728   
29              0.734694              0.000000                 0.563107   
...                  ...                   ...                      ...   
10690           0.571429              0.000000                 0.446602   
10691           0.734694              0.000000                 0.446602   
10692           0.244898              0.000000                 0.679612   
10693           0.448980              0.000000                 0.660194   
10694           0.632653              0.000000                 0.427184   
10695           0.612245              0.000000                 0.504854   
10696           0.306122              0.000000                 0.757282   
10697           0.428571              0.000000                 0.718447   
10698           0.551020              0.000000                 0.582524   
10699           0.469388              0.000000                 0.504854   
10700           0.489796              0.000000                 0.533981   
10701           0.551020              0.000000                 0.533981   
10702           0.673469              0.000000                 0.398058   
10703           0.612245              0.000000                 0.543689   
10704           0.428571              0.000000                 0.553398   
10705           0.612245              0.000000                 0.514563   
10706           0.428571              0.000000                 0.679612   
10707           0.591837              0.000000                 0.407767   
10708           0.530612              0.000000                 0.514563   
10709           0.510204              0.000000                 0.621359   
10710           0.673469              0.000000                 0.417476   
10711           0.510204        

In [236]:
import pandas as pd
data = pd.read_csv('IsusV3.csv', delimiter = ',').reset_index(drop=True)
# data
# data

In [238]:
data1 = data.drop(['Target'], axis=1).fillna(0)
# data1 = data1.values
y = data[['Target']].values
data1.shape
# y

(10720, 135)

In [239]:
x = data1.to_dict('records')

In [240]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import LabelEncoder
vec = DictVectorizer()
x = vec.fit_transform(x).toarray()
x.shape

(10720, 172)

In [241]:
print(x,y,x.shape,y.shape)

[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]] [[1.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [1.]] (10720, 172) (10720, 1)


In [301]:
x_train = x[:8000][:]
y_train = y[:8000][:]
# x_train2 = x[6000:8000][:]
# y_train2 = y[6000:8000][:]
x_val = x[8000:][:]
y_val = y[8000:][:]
print(x_train.shape,y_train.shape,x_val.shape,y_val.shape)

(8000, 172) (8000, 1) (2720, 172) (2720, 1)


In [302]:
from imblearn.over_sampling import SMOTE
# smote = SMOTE(ratio='minority')
sm = SMOTE(random_state=42)
# x_sm, y_sm = sm.fit_sample(x_train, y_train)
# x_sm, y_sm = x_train, y_train
x_sm, y_sm = sm.fit_sample(x_train, y_train)


print(x_sm.shape,y_sm.shape)


# x_sm2, y_sm2 = sm.fit_sample(x_train2, y_train2)
# print(x_sm2.shape,y_sm2.shape)

(15018, 172) (15018,)


C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [178]:
x_sm.shape
# x_sm = x_sm[:,np.array([9,10,11,136,148,154,156,158,159])]
# x_sm.shape

(15096, 9)

In [311]:
import os
import numpy as np
import datetime

import scipy.stats as st

from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier, VotingClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import LabelBinarizer
from xgboost import XGBClassifier
from sklearn.externals import joblib

from lightgbm.sklearn import LGBMClassifier

n_jobs = -1
n_iter = 20
n_iter_nt = 3
cv = 5
seed=42
n_features= x_sm.shape[1]

In [309]:
# from sklearn.feature_extraction import DictVectorizer
# v = DictVectorizer(sparse=False)
# d = [{'height': 1, 'length': 0, 'width': 1},{'height': 2, 'length': 1, 'width': 0},{'height': 1, 'length': 3, 'width': 2}]
# v.fit_transform(d)
from sklearn.metrics import f1_score , precision_score , recall_score
model = log
log.fit(x_sm, y_sm)
y_pre = log.predict(x_val)
f1_1  = f1_score(y_val, y_pre, average='binary')
y_pre_2 = log.predict(x_train)
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1_1,f1_2)

0.08949416342412453 0.18036529680365299


In [312]:
estimator = XGBClassifier(nthreads=-1)
objective = 'binary:logistic'

# Parameter for XGBoost
params = {  
    "n_estimators": st.randint(3, 40),
    "max_depth": st.randint(3, 30),
    "learning_rate": st.uniform(0.05, 0.4),
    "colsample_bytree": st.beta(10, 1),
    "subsample": st.beta(10, 1),
    "gamma": st.uniform(0, 10),
    'objective': [objective],
    'scale_pos_weight': st.randint(0, 2),
    "min_child_weight": st.expon(0, 50),
    "seed": [seed],
}
xgb = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 


In [313]:
estimator = LogisticRegression()
# Parameter for LogisticRegression
params = {
    "penalty": ['l2'],
    "C": [0.001, 0.01, 0.1, 1, 10],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1],
    "solver": ['newton-cg', 'lbfgs', 'liblinear', 'sag'],
    "max_iter": st.randint(50, 100),
    'random_state': [seed],
} 
log = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [314]:
estimator = KNeighborsClassifier()
# Parameter for KNeighborsClassifier
params = {
    "n_neighbors": st.randint(2, 50),
    "weights": ['uniform', 'distance'],
    "algorithm": ['ball_tree', 'kd_tree', 'brute'],
    "leaf_size": st.randint(10, 30),
    "p": st.randint(1, 2),
}
knn = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter_nt) 

In [315]:
estimator = RandomForestClassifier()
# Parameter for RandomForestClassifier
params = {
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True, False],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
rnf = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [316]:
estimator = ExtraTreesClassifier()
# Parameter for ExtraTreesClassifier
params = {
    "n_estimators": st.randint(5, 50),
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True],
    "oob_score": [True],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
ext = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [317]:
estimator = AdaBoostClassifier()
# Parameter for AdaBoost
params = { 
    'n_estimators':st.randint(10, 100), 
    'learning_rate':st.beta(10, 1), 
    'algorithm':['SAMME', 'SAMME.R'],
    'random_state': [seed],
}
ada = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [318]:
estimator = SVC()
# Parameter for SVC
params = {  
    'C':[0.001, 0.01, 0.1, 1, 10], 
    'degree': st.randint(1, 10),
    'shrinking': [True, False],
    'probability': [True],
    'tol': [1e-3],
    'random_state': [seed],
}
svc = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter_nt)

In [319]:
estimator = LGBMClassifier(nthread=-1)
# Parameter for LGBMClassifier
params = {  
    "boosting_type": ["gbdt","rf","dart"],
    "colsample_bytree": st.beta(10, 1),
    "learning_rate": st.uniform(0.05, 0.4),
    "max_depth": st.randint(3, 30),
    "min_child_weight": st.expon(0, 50),
    "n_estimators": st.randint(3, 40),
    "num_leaves": st.randint(30, 50),
    'objective': [objective],
    "subsample": st.beta(10, 1),
    "seed": [seed],
}

lgb = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter_nt)

In [ ]:
xgb.fit(x_sm,y_sm)
log.fit(x_sm,y_sm)
knn.fit(x_sm,y_sm)
rnf.fit(x_sm,y_sm)
ext.fit(x_sm,y_sm)
ada.fit(x_sm,y_sm)
lgb.fit(x_sm,y_sm)
# svc.fit(x_sm,y_sm)

# y_pre_2 = xgb.predict(x_train)
# f1_2  = f1_score(y_train, y_pre_2, average='binary')
# joblib.dump(xgb, 'xgb.pkl') 
# joblib.dump(log, 'log.pkl') 
# joblib.dump(knn, 'knn.pkl') 
# joblib.dump(rnf, 'rnf.pkl') 
# joblib.dump(ext, 'ext.pkl') 
# joblib.dump(ada, 'ada.pkl') 
# joblib.dump(svc, 'svc.pkl') 
# vote2 = joblib.load('vote.pkl') 



In [254]:
joblib.dump(xgb, 'xgb.pkl') 
joblib.dump(log, 'log.pkl') 
joblib.dump(knn, 'knn.pkl') 
joblib.dump(rnf, 'rnf.pkl') 
joblib.dump(ext, 'ext.pkl') 
joblib.dump(ada, 'ada.pkl') 
joblib.dump(lgb, 'lgb.pkl') 
joblib.dump(svc, 'svc.pkl') 

['svc.pkl']

In [216]:
# xgb = joblib.load('xgb.pkl')
# log = joblib.load('log.pkl') 
# knn = joblib.load('knn.pkl') 
# rnf = joblib.load('rnf.pkl') 
# ext = joblib.load('ext.pkl') 
# ada = joblib.load('ada.pkl') 
# svc = joblib.load('svc.pkl') 

In [189]:
x_val = x_val[:,np.array([9,10,11,136,148,154,156,158,159])]
x_train = x_train[:,np.array([9,10,11,136,148,154,156,158,159])]

In [253]:
from sklearn.metrics import f1_score , precision_score , recall_score
y_pre = xgb.predict(x_val)
y_pre_2 = xgb.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'xgb')
y_pre = log.predict(x_val)
y_pre_2 = log.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'log')
y_pre = knn.predict(x_val)
y_pre_2 = knn.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'knn')
y_pre = rnf.predict(x_val)
y_pre_2 = rnf.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'rnf')
y_pre = ext.predict(x_val)
y_pre_2 = ext.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'ext')
y_pre = ada.predict(x_val)
y_pre_2 = ada.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'ada')
y_pre = svc.predict(x_val)
y_pre_2 = svc.predict(x_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'svc')

C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.01492537313432836 0.04961832061068703 xgb
0.09554655870445344 0.1600933488914819 log
0.06756756756756756 1.0 knn
0.0 0.41033434650455924 rnf
0.0 0.6809015421115066 ext
0.05161290322580645 0.07932011331444759 ada
0.013793103448275864 0.22266204849084612 svc


In [268]:
a = log.best_estimator_.coef_
a = ada.best_estimator_.feature_importances_
a

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00834905, 0.        , 0.        , 0.        , 0.00920586,
       0.01012321, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01370775, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00632684, 0.        ,
       0.        , 0.04433919, 0.00605415, 0.        , 0.        ,
       0.02054843, 0.        , 0.03315179, 0.08930309, 0.02958396,
       0.08670702, 0.05670399, 0.01239347, 0.02800984, 0.        ,
       0.01946984, 0.01227604, 0.02419606, 0.        , 0.        ,
       0.04129673, 0.        , 0.        , 0.        , 0.        ,
       0.02704987, 0.        , 0.01335804, 0.        , 0.        ,
       0.02205143, 0.        , 0.        , 0.        , 0.01327

In [289]:
# print(np.argwhere(a>0.01),np.argwhere(a<-0.01))
# print(np.argwhere(a!=0))
b = np.argwhere(a!=0)
# np.reshape(b,(b.shape[]))
b = b.ravel()
print(b,np.array([9,10,11,136,148,154,156,158,159]))

[  5   9  10  31  38  41  42  45  47  48  49  50  51  52  53  55  56  57
  60  65  67  70  74  75  77  80  82  83  84 120 125 129 142 143 144 146
 147 149 152 153 154 158 160 164 170] [  9  10  11 136 148 154 156 158 159]


In [143]:
print(np.argwhere(a>0.01),np.argwhere(a<-0.01))

[[  0   9]
 [  0  10]
 [  0  11]
 [  0 136]
 [  0 148]
 [  0 156]
 [  0 158]
 [  0 159]] [[  0 154]]


In [290]:
x_sm2 = x_sm[:,np.array(b)]
x_sm2.shape

(15018, 45)

In [291]:
re1 = xgb.predict_proba(x_sm)
re2 = log.predict_proba(x_sm)
re3 = knn.predict_proba(x_sm)
re4 = rnf.predict_proba(x_sm)
re5 = ext.predict_proba(x_sm)
re6 = ada.predict_proba(x_sm)
re7 = svc.predict_proba(x_sm)

In [293]:
xx = x_sm2

In [294]:
# test = xgb.predict_proba(x_val)
# test[:,0]


re_1 = re1[:,0]
re_2 = re2[:,0]
re_3 = re3[:,0]
re_4 = re4[:,0]
re_5 = re5[:,0]
re_6 = re6[:,0]
re_7 = re7[:,0]

re_1 = np.reshape(re_1, (re_1.shape[0],1))
re_2 = np.reshape(re_2, (re_2.shape[0],1))
re_3 = np.reshape(re_3, (re_3.shape[0],1))
re_4 = np.reshape(re_4, (re_4.shape[0],1))
re_5 = np.reshape(re_5, (re_5.shape[0],1))
re_6 = np.reshape(re_6, (re_6.shape[0],1))
re_7 = np.reshape(re_7, (re_7.shape[0],1))
# xx = x_sm
xx = np.concatenate((xx, re_1), axis=1)
xx = np.concatenate((xx, re_2), axis=1)
xx = np.concatenate((xx, re_3), axis=1)
xx = np.concatenate((xx, re_4), axis=1)
xx = np.concatenate((xx, re_5), axis=1)
xx = np.concatenate((xx, re_6), axis=1)
xx = np.concatenate((xx, re_7), axis=1)

In [295]:
xx.shape

(15018, 52)

In [296]:
n_jobs = -1
n_iter = 30
cv = 5
seed=42
n_features=xx.shape[1]

estimator = XGBClassifier(nthreads=-1)
objective = 'binary:logistic'

# Parameter for XGBoost
params = {  
    "n_estimators": st.randint(3, 40),
    "max_depth": st.randint(3, 30),
    "learning_rate": st.uniform(0.05, 0.4),
    "colsample_bytree": st.beta(10, 1),
    "subsample": st.beta(10, 1),
    "gamma": st.uniform(0, 10),
    'objective': [objective],
    'scale_pos_weight': st.randint(0, 2),
    "min_child_weight": st.expon(0, 50),
    "seed": [seed],
}
xgb2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

estimator = LogisticRegression()
# Parameter for LogisticRegression
params = {
    "penalty": ['l2'],
    "C": [0.001, 0.01, 0.1, 1, 10],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1],
    "solver": ['newton-cg', 'lbfgs', 'liblinear', 'sag'],
    "max_iter": st.randint(50, 100),
    'random_state': [seed],
} 
log2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

estimator = RandomForestClassifier()
# Parameter for RandomForestClassifier
params = {
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True, False],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
rnf2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

estimator = ExtraTreesClassifier()
# Parameter for ExtraTreesClassifier
params = {
    "n_estimators": st.randint(5, 50),
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True],
    "oob_score": [True],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
ext2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

estimator = AdaBoostClassifier()
# Parameter for AdaBoost
params = { 
    'n_estimators':st.randint(10, 100), 
    'learning_rate':st.beta(10, 1), 
    'algorithm':['SAMME', 'SAMME.R'],
    'random_state': [seed],
}
ada2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [297]:
xgb2.fit(xx,y_sm)
log2.fit(xx,y_sm)
rnf2.fit(xx,y_sm)
ext2.fit(xx,y_sm)
ada2.fit(xx,y_sm)


# joblib.dump(xgb2, 'xgb2.pkl') 
# joblib.dump(log2, 'log2.pkl') 
# joblib.dump(rnf2, 'rnf2.pkl') 

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None),
          fit_params=None, iid=True, n_iter=30, n_jobs=-1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001CAB2538358>, 'learning_rate': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001CAB2538FD0>, 'algorithm': ['SAMME', 'SAMME.R'], 'random_state': [42]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [274]:
xx.shape

(15018, 179)

In [264]:
vote_list = [('xgb2', xgb2), ('log2', log2), ('rnf2', rnf2), ('ext2', ext2)]
vote2 = VotingClassifier(estimators=vote_list, voting='soft')
vote2.fit(xx, y_sm)
# joblib.dump(vote2, 'vote2.pkl') 

VotingClassifier(estimators=[('xgb2', RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,...obs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0))],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)

In [119]:
xx_val.shape
re_1.shape

(15096, 1)

In [298]:
xx_val = x_val[:,np.array(b)]
xx_train = x_train[:,np.array(b)]

# xx_val = x_val
# xx_train = x_train

# re1 = xgb2.predict_proba(x_sm)
# re2 = log.predict_proba(x_sm)
# re3 = knn.predict_proba(x_sm)

re11 = xgb.predict_proba(x_val)
re12 = log.predict_proba(x_val)
re13 = knn.predict_proba(x_val)
re14 = rnf.predict_proba(x_val)
re15 = ext.predict_proba(x_val)
re16 = ada.predict_proba(x_val)
re17 = svc.predict_proba(x_val)

re_11 = re11[:,0]
re_12 = re12[:,0]
re_13 = re13[:,0]
re_14 = re14[:,0]
re_15 = re15[:,0]
re_16 = re16[:,0]
re_17 = re17[:,0]

re_11 = np.reshape(re_11, (re_11.shape[0],1))
re_12 = np.reshape(re_12, (re_12.shape[0],1))
re_13 = np.reshape(re_13, (re_13.shape[0],1))
re_14 = np.reshape(re_14, (re_14.shape[0],1))
re_15 = np.reshape(re_15, (re_15.shape[0],1))
re_16 = np.reshape(re_16, (re_16.shape[0],1))
re_17 = np.reshape(re_17, (re_17.shape[0],1))


xx_val = np.concatenate((xx_val, re_11), axis=1)
xx_val = np.concatenate((xx_val, re_12), axis=1)
xx_val = np.concatenate((xx_val, re_13), axis=1)
xx_val = np.concatenate((xx_val, re_14), axis=1)
xx_val = np.concatenate((xx_val, re_15), axis=1)
xx_val = np.concatenate((xx_val, re_16), axis=1)
xx_val = np.concatenate((xx_val, re_17), axis=1)

re21 = xgb.predict_proba(x_train)
re22 = log.predict_proba(x_train)
re23 = knn.predict_proba(x_train)
re24 = rnf.predict_proba(x_train)
re25 = ext.predict_proba(x_train)
re26 = ada.predict_proba(x_train)
re27 = svc.predict_proba(x_train)

re_21 = re21[:,0]
re_22 = re22[:,0]
re_23 = re23[:,0]
re_24 = re24[:,0]
re_25 = re25[:,0]
re_26 = re26[:,0]
re_27 = re27[:,0]

re_21 = np.reshape(re_21, (re_21.shape[0],1))
re_22 = np.reshape(re_22, (re_22.shape[0],1))
re_23 = np.reshape(re_23, (re_23.shape[0],1))
re_24 = np.reshape(re_24, (re_24.shape[0],1))
re_25 = np.reshape(re_25, (re_25.shape[0],1))
re_26 = np.reshape(re_26, (re_26.shape[0],1))
re_27 = np.reshape(re_27, (re_27.shape[0],1))


xx_train = np.concatenate((xx_train, re_21), axis=1)
xx_train = np.concatenate((xx_train, re_22), axis=1)
xx_train = np.concatenate((xx_train, re_23), axis=1)
xx_train = np.concatenate((xx_train, re_24), axis=1)
xx_train = np.concatenate((xx_train, re_25), axis=1)
xx_train = np.concatenate((xx_train, re_26), axis=1)
xx_train = np.concatenate((xx_train, re_27), axis=1)

In [300]:
xx_train.shape

(8000, 52)

In [299]:
# xx_train.shape
y_pre = xgb2.predict(xx_val)
y_pre_2 = xgb2.predict(xx_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'xgb2')
y_pre = log2.predict(xx_val)
y_pre_2 = log2.predict(xx_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'log2')
y_pre = rnf2.predict(xx_val)
y_pre_2 = rnf2.predict(xx_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'rnf2')
y_pre = ext2.predict(xx_val)
y_pre_2 = ext2.predict(xx_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'ext2')
y_pre = ada2.predict(xx_val)
y_pre_2 = ada2.predict(xx_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'ada2')

0.06756756756756756 1.0 xgb2
0.0665083135391924 1.0 log2
0.06756756756756756 1.0 rnf2
0.0647887323943662 1.0 ext2
0.06756756756756756 1.0 ada2


C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [265]:
# vote2.feature_importances_
y_pre = vote2.predict(xx_val)
y_pre_2 = vote2.predict(xx_train)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'vote2')

0.06756756756756756 1.0 vote2


C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [40]:
vote2.score(xx, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [45]:
# predict process
re1 = xgb.predict(X)
re2 = log.predict(X)
re3 = knn.predict(X)
re4 = rnf.predict(X)
re5 = ext.predict(X)
re6 = ada.predict(X)
re7 = svc.predict(X)

re_1 = np.reshape(re1, (re1.shape[0],1))
re_2 = np.reshape(re2, (re2.shape[0],1))
re_3 = np.reshape(re3, (re3.shape[0],1))
re_4 = np.reshape(re4, (re4.shape[0],1))
re_5 = np.reshape(re5, (re5.shape[0],1))
re_6 = np.reshape(re6, (re6.shape[0],1))
re_7 = np.reshape(re7, (re7.shape[0],1))

xx = np.concatenate((xx, re_1), axis=1)
xx = np.concatenate((xx, re_2), axis=1)
xx = np.concatenate((xx, re_3), axis=1)
xx = np.concatenate((xx, re_4), axis=1)
xx = np.concatenate((xx, re_5), axis=1)
xx = np.concatenate((xx, re_6), axis=1)
xx = np.concatenate((xx, re_7), axis=1)
print(xx,xx.shape)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[  6.46907649   4.25070317  -8.63694437 ...  85.          69.
   85.        ]
 [  6.48856404   9.37957037  10.32791736 ...  64.          69.
   64.        ]
 [  8.37392753 -10.14342267  -3.52753613 ...  93.          69.
   93.        ]
 ...
 [  7.86551596   6.19525794   4.773955   ...  98.          69.
   98.        ]
 [-10.41156442   1.40054826  -1.97349572 ...  80.          67.
   80.        ]
 [  7.40908901  -7.3908382   10.78350645 ...  91.          69.
   91.        ]] (10000, 31)


In [ ]:
y_final = vote2.predect()

In [ ]:
f1_score(y_val, y_final, average='macro')

In [233]:
y_sm2.shape

(3790,)

In [231]:
vote_list = [('xgb', xgb), ('log', log), ('knn', knn), ('rnf', rnf), ('ext', ext), ('ada', ada), ('svc', svc)]
# vote_list = [('xgb', xgb), ('log', log) ,('rnf', rnf), ('ext', ext), ('ada', ada)]
vote = VotingClassifier(estimators=vote_list, voting='soft')
vote.fit(x_sm2, y_sm2)
# y_pre = vote.predict(x_sm)
y_pre = vote.predict(x_val)
y_pre_2 = vote.predict(x_train2)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1,f1_2,'vote')

C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)
C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


ValueError: Found input variables with inconsistent numbers of samples: [6000, 2000]

In [235]:
y_pre = vote.predict(x_val)
y_pre_2 = vote.predict(x_train2)
f1  = f1_score(y_val, y_pre, average='binary')
f1_2  = f1_score(y_train2, y_pre_2, average='binary')
print(f1,f1_2,'vote')

C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.011363636363636364 0.9952153110047847 vote


C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [32]:
xgb.best_estimator_.feature_importances_

array([0.        , 0.        , 0.        , 0.        , 0.00546448,
       0.        , 0.0273224 , 0.01092896, 0.00546448, 0.01092896,
       0.00546448, 0.00546448, 0.03278688, 0.04918033, 0.01639344,
       0.00546448, 0.03278688, 0.01092896, 0.01092896, 0.        ,
       0.        , 0.        , 0.01639344, 0.00546448, 0.01639344,
       0.01639344, 0.01092896, 0.00546448, 0.00546448, 0.        ,
       0.01639344, 0.02185792, 0.02185792, 0.01092896, 0.01092896,
       0.00546448, 0.        , 0.        , 0.00546448, 0.        ,
       0.        , 0.        , 0.        , 0.00546448, 0.        ,
       0.        , 0.        , 0.        , 0.00546448, 0.        ,
       0.01639344, 0.        , 0.00546448, 0.        , 0.        ,
       0.00546448, 0.        , 0.        , 0.00546448, 0.        ,
       0.00546448, 0.        , 0.00546448, 0.        , 0.        ,
       0.        , 0.00546448, 0.        , 0.01092896, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [19]:
y_pre

array([85, 64, 93, ..., 98, 80, 91])

In [68]:
from sklearn.metrics import f1_score , precision_score , recall_score

In [63]:
f1_score(y, y_pre, average='binary')

0.0032520325203252032

In [73]:
precision_score(y, y_pre,pos_label=1, average='binary')

1.0

In [72]:
recall_score(y, y_pre,pos_label=1, average=None)

array([1.        , 0.00162866])

In [62]:
print(y,y_pre)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]] [0. 0. 0. ... 0. 0. 0.]


In [76]:
y_pre.sum()

1.0

In [57]:
joblib.dump(vote, 'vote.pkl') 
vote2 = joblib.load('vote.pkl') 

['vote.pkl']

In [25]:
vote2 = joblib.load('vote.pkl') 

In [26]:
vote2.score(X, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [27]:
vote2

VotingClassifier(estimators=[('xgb', RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=nan, n_estimators=100,
 ...obs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0))],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)