In [1]:
>>> from sklearn.model_selection import cross_val_score
>>> from sklearn.datasets import make_blobs
>>> from sklearn.ensemble import RandomForestClassifier
>>> from sklearn.ensemble import ExtraTreesClassifier
>>> from sklearn.tree import DecisionTreeClassifier

In [2]:
X, y = make_blobs(n_samples=10000, n_features=10, centers=100,random_state=0)

In [6]:
X

array([[  6.46907649,   4.25070317,  -8.63694437, ...,  -0.48172814,
         -6.44996141,  -2.65984972],
       [  6.48856404,   9.37957037,  10.32791736, ...,   3.37542134,
          7.41273719,  -9.72284371],
       [  8.37392753, -10.14342267,  -3.52753613, ...,  -7.31536045,
         -2.33070872,   6.44087163],
       ...,
       [  7.86551596,   6.19525794,   4.773955  , ...,   4.93452091,
         -4.52137856,   6.28178851],
       [-10.41156442,   1.40054826,  -1.97349572, ...,  -3.18210433,
          7.59487579,   4.62753678],
       [  7.40908901,  -7.3908382 ,  10.78350645, ...,  -3.26219501,
          5.73727272,  -4.97354916]])

In [5]:
y

array([85, 64, 93, ..., 98, 80, 91])

In [7]:
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)

In [8]:
scores = cross_val_score(clf, X, y)
scores

array([0.97852941, 0.98212121, 0.97757576])

In [9]:
clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [10]:
scores = cross_val_score(clf, X, y)
scores

array([0.97852941, 0.98212121, 0.97757576])

In [14]:
import scipy.stats as st
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

In [15]:
estimator = XGBClassifier(nthreads=-1)
params = {  
            "n_estimators": st.randint(3, 40),
            "max_depth": st.randint(3, 40),
            "learning_rate": st.uniform(0.05, 0.4),
            "colsample_bytree": st.beta(, 1),
            "subsample": st.beta(10, 1),
            "gamma": st.uniform(0, 10),
            'objective': ['binary:logistic'],
            'scale_pos_weight': st.randint(0, 2),
            "min_child_weight": st.expon(0, 50),
        }

# Random Search Training with 5 folds Cross Validation
clf = RandomizedSearchCV(estimator, params, cv=5,
                         n_jobs=1, n_iter=2) 

In [16]:
clf.fit(X, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `arra

RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, nthreads=-1, objective='binary:logistic',
       random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
       seed=None, silent=True, subsample=1),
          fit_params=None, iid=True, n_iter=2, n_jobs=1,
          param_distributions={'n_estimators': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA441AC8>, 'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA441C18>, 'learning_rate': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA441D68>, 'cols...F8>, 'min_child_weight': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001FCCA440BA8>},
          pre_dispatch='2*n_jobs', random_state=None, refit=

In [17]:
scores = clf.score(X, y)
scores

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9906

In [18]:
clf.predict(X)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([85, 64, 93, ..., 98, 80, 91])

In [20]:
y

array([85, 64, 93, ..., 98, 80, 91])

In [23]:
clf2 = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)
clf2.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [24]:
clf2.score(X, y)

1.0

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `arra

VotingClassifier(estimators=[('clf', RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
...         min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best'))],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)

In [27]:
vote.score(X, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [31]:
yy = vote.predict(X)
yy

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([85, 64, 93, ..., 98, 80, 91])

In [29]:
X

array([[  6.46907649,   4.25070317,  -8.63694437, ...,  -0.48172814,
         -6.44996141,  -2.65984972],
       [  6.48856404,   9.37957037,  10.32791736, ...,   3.37542134,
          7.41273719,  -9.72284371],
       [  8.37392753, -10.14342267,  -3.52753613, ...,  -7.31536045,
         -2.33070872,   6.44087163],
       ...,
       [  7.86551596,   6.19525794,   4.773955  , ...,   4.93452091,
         -4.52137856,   6.28178851],
       [-10.41156442,   1.40054826,  -1.97349572, ...,  -3.18210433,
          7.59487579,   4.62753678],
       [  7.40908901,  -7.3908382 ,  10.78350645, ...,  -3.26219501,
          5.73727272,  -4.97354916]])

In [30]:
import numpy as np

In [38]:
test = np.concatenate((yy, yy), axis=1)
test

AxisError: axis 1 is out of bounds for array of dimension 1

In [37]:
test.shape

(20000,)

In [53]:
test2 = np.reshape(yy, (yy.shape[0],1))

In [50]:
yy.shape

(10000,)

In [47]:
xx=X

In [49]:
xx.shape

(10000, 10)

In [54]:
test2 = np.reshape(yy, (yy.shape[0],1))
np.concatenate((xx, test2), axis=1)

array([[  6.46907649,   4.25070317,  -8.63694437, ...,  -6.44996141,
         -2.65984972,  85.        ],
       [  6.48856404,   9.37957037,  10.32791736, ...,   7.41273719,
         -9.72284371,  64.        ],
       [  8.37392753, -10.14342267,  -3.52753613, ...,  -2.33070872,
          6.44087163,  93.        ],
       ...,
       [  7.86551596,   6.19525794,   4.773955  , ...,  -4.52137856,
          6.28178851,  98.        ],
       [-10.41156442,   1.40054826,  -1.97349572, ...,   7.59487579,
          4.62753678,  80.        ],
       [  7.40908901,  -7.3908382 ,  10.78350645, ...,   5.73727272,
         -4.97354916,  91.        ]])

In [1]:
import pandas as pd

In [18]:
data = pd.read_csv('IsusV2forTrain.csv', delimiter = ',').reset_index(drop=True)
data

Target  Ad_amount  UserAge  AccAge  AgeAtOpenAcc  CreditSumcat1  \
0         0.0          0       55      28            27    2963.545233   
1         0.0          0       46      39             7    6170.049250   
2         0.0          0       68      41            27      54.359237   
3         0.0          0       53      39            14       0.000000   
4         0.0          0       52      33            19       0.000000   
5         0.0          0       62      36            26       0.000000   
6         0.0          0       60      44            16       0.000000   
7         0.0          0       64      47            17       0.000000   
8         0.0          0       52      46             6    1624.552270   
9         0.0          1       45      46            -1       0.000000   
10        0.0          1       73      31            42       0.000000   
11        0.0          0       47      40             7    4374.962757   
12        0.0          1       55      39            16       0.000000   
13        0.0          0       64      29            35       0.000000   
14        0.0          0       51      34            17       0.000000   
15        0.0          0       42      42             0       0.000000   
16        0.0          0       61      29            32       0.000000   
17        0.0          0       68      39            29       0.000000   
18        0.0          0       49      47             2       0.000000   
19        0.0          0       43      33            10       0.000000   
20        0.0          0       58      34            24       0.000000   
21        0.0          0       47      39             8    3494.945315   
22        0.0          0       76      42            34    3730.158362   
23        0.0          0       41      43            -2       0.000000   
24        0.0          0       44      40             4       0.000000   
25        0.0          1       75      26            49       0.000000   
26        0.0          0       40      35             5       0.000000   
27        0.0          0       57      46            11       0.000000   
28        1.0          0       54      37            17   24129.656948   
29        0.0          0       49      32            17       0.000000   
...       ...        ...      ...     ...           ...            ...   
10690     1.0          0       59      32            27     503.435321   
10691     0.0          0       47      36            11       0.000000   
10692     0.0          0       50      36            14   10878.956149   
10693     0.0          0       48      39             9       0.000000   
10694     0.0          0       55      39            16       0.000000   
10695     0.0          0       60      46            14       0.000000   
10696     0.0          0       45      35            10    9649.509734   
10697     0.0          0       75      36            39     696.099208   
10698     0.0          0       54      31            23       0.000000   
10699     1.0          0       68      37            31       0.000000   
10700     0.0          0       66      32            34       0.000000   
10701     0.0          0       51      41            10       0.000000   
10702     0.0          0       59      50             9       0.000000   
10703     0.0          0       61      37            24       0.000000   
10704     0.0          0       58      29            29    1396.382581   
10705     0.0          0       63      37            26       0.000000   
10706     0.0          0       51      37            14       0.000000   
10707     0.0          0       83      40            43       0.000000   
10708     0.0          0       57      33            24       0.000000   
10709     0.0          0       51      36            15       0.000000   
10710     0.0          0       55      36            19       0.000000   
10711     0.0          1       65      32            33       0.000000   
10712     0

In [19]:
data1 = data.drop(['Target'], axis=1).fillna(0)
# data1 = data1.values
y = data[['Target']].values
data1.shape
# y

(10720, 134)

In [20]:
x = data1.to_dict('records')

In [21]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import LabelEncoder
vec = DictVectorizer()
x = vec.fit_transform(x).toarray()
x.shape

(10720, 166)

In [22]:
print(x,y,x.shape,y.shape)

[[   28.             0.             0.         ... 11670.96058694
     55.             0.        ]
 [   39.             0.             0.         ...   173.17607771
     46.             0.        ]
 [   41.             0.             0.         ... 11670.96058694
     68.             0.        ]
 ...
 [   40.             0.             0.         ...   222.44877207
     48.             0.        ]
 [   36.             0.             0.         ...  1781.51391167
     49.             0.        ]
 [   39.             0.             0.         ... 11670.96058694
     63.             0.        ]] [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]] (10720, 166) (10720, 1)


In [23]:
x_train = x[:8000][:]
y_train = y[:8000][:]
x_val = x[8000:][:]
y_val = y[8000:][:]
print(x_train.shape,y_train.shape,x_val.shape,y_val.shape)

(8000, 166) (8000, 1) (2720, 166) (2720, 1)


In [24]:
from imblearn.over_sampling import SMOTE
# smote = SMOTE(ratio='minority')
sm = SMOTE(random_state=42)
# x_sm, y_sm = sm.fit_sample(x_train, y_train)
# x_sm, y_sm = x_train, y_train
x_sm, y_sm = sm.fit_sample(x_train, y_train)
print(x_sm,y_sm,x_sm.shape,y_sm.shape)

[[2.80000000e+01 0.00000000e+00 0.00000000e+00 ... 1.16709606e+04
  5.50000000e+01 0.00000000e+00]
 [3.90000000e+01 0.00000000e+00 0.00000000e+00 ... 1.73176078e+02
  4.60000000e+01 0.00000000e+00]
 [4.10000000e+01 0.00000000e+00 0.00000000e+00 ... 1.16709606e+04
  6.80000000e+01 0.00000000e+00]
 ...
 [3.53827322e+01 0.00000000e+00 1.25702923e-01 ... 1.86861756e+02
  5.72401591e+01 0.00000000e+00]
 [4.56421625e+01 0.00000000e+00 0.00000000e+00 ... 3.46258254e+03
  4.57753146e+01 0.00000000e+00]
 [3.01673775e+01 0.00000000e+00 6.82269453e-01 ... 1.16709606e+04
  5.34581556e+01 0.00000000e+00]] [0. 0. 0. ... 1. 1. 1.] (15096, 166) (15096,)


C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [101]:
x_sm.shape[1]

137

In [25]:
import os
import numpy as np
import datetime

import scipy.stats as st

from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier, VotingClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import LabelBinarizer
from xgboost import XGBClassifier
from sklearn.externals import joblib

n_jobs = -1
n_iter = 20
cv = 5
seed=42
n_features= x_sm.shape[1]

In [27]:
# from sklearn.feature_extraction import DictVectorizer
# v = DictVectorizer(sparse=False)
# d = [{'height': 1, 'length': 0, 'width': 1},{'height': 2, 'length': 1, 'width': 0},{'height': 1, 'length': 3, 'width': 2}]
# v.fit_transform(d)
from sklearn.metrics import f1_score , precision_score , recall_score

xgb.fit(x_sm, y_sm)
y_pre = xgb.predict(x_val)
f1_1  = f1_score(y_val, y_pre, average='binary')
y_pre_2 = xgb.predict(x_train)
f1_2  = f1_score(y_train, y_pre_2, average='binary')
print(f1_1,f1_2)

0.012121212121212121 0.10460251046025106


C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [17]:
xgb.predict(x_val)

C:\Users\EBM_IT_01\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


array([0., 0., 0., ..., 0., 0., 0.])

In [26]:
estimator = XGBClassifier(nthreads=-1)
objective = 'binary:logistic'

# Parameter for XGBoost
params = {  
    "n_estimators": st.randint(3, 40),
    "max_depth": st.randint(3, 30),
    "learning_rate": st.uniform(0.05, 0.4),
    "colsample_bytree": st.beta(10, 1),
    "subsample": st.beta(10, 1),
    "gamma": st.uniform(0, 10),
    'objective': [objective],
    'scale_pos_weight': st.randint(0, 2),
    "min_child_weight": st.expon(0, 50),
    "seed": [seed],
}
xgb = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 


In [105]:
estimator = LogisticRegression()
# Parameter for LogisticRegression
params = {
    "penalty": ['l2'],
    "C": [0.001, 0.01, 0.1, 1, 10],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1],
    "solver": ['newton-cg', 'lbfgs', 'liblinear', 'sag'],
    "max_iter": st.randint(50, 100),
    'random_state': [seed],
} 
log = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [106]:
estimator = KNeighborsClassifier()
# Parameter for KNeighborsClassifier
params = {
    "n_neighbors": st.randint(2, 50),
    "weights": ['uniform', 'distance'],
    "algorithm": ['ball_tree', 'kd_tree', 'brute'],
    "leaf_size": st.randint(10, 30),
    "p": st.randint(1, 2),
}
knn = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [107]:
estimator = RandomForestClassifier()
# Parameter for RandomForestClassifier
params = {
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True, False],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
rnf = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [108]:
estimator = ExtraTreesClassifier()
# Parameter for ExtraTreesClassifier
params = {
    "n_estimators": st.randint(5, 50),
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True],
    "oob_score": [True],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
ext = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [109]:
estimator = AdaBoostClassifier()
# Parameter for AdaBoost
params = { 
    'n_estimators':st.randint(10, 100), 
    'learning_rate':st.beta(10, 1), 
    'algorithm':['SAMME', 'SAMME.R'],
    'random_state': [seed],
}
ada = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [110]:
estimator = SVC()
# Parameter for SVC
params = {  
    'C':[0.001, 0.01, 0.1, 1, 10], 
    'degree': st.randint(1, 10),
    'shrinking': [True, False],
    'probability': [True],
    'tol': [1e-3],
    'random_state': [seed],
}
svc = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [30]:
xgb.fit(X,y)
log.fit(X,y)
knn.fit(X,y)
rnf.fit(X,y)
ext.fit(X,y)
ada.fit(X,y)
svc.fit(X,y)

D:\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


RandomizedSearchCV(cv=5, error_score='raise',
          estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
          fit_params=None, iid=True, n_iter=2, n_jobs=2,
          param_distributions={'C': [0.001, 0.01, 0.1, 1, 10], 'degree': <scipy.stats._distn_infrastructure.rv_frozen object at 0x00000234CE197AC8>, 'shrinking': [True, False], 'probability': [True], 'tol': [0.001], 'random_state': [42]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [31]:
re1 = xgb.predict(X)
re2 = log.predict(X)
re3 = knn.predict(X)
re4 = rnf.predict(X)
re5 = ext.predict(X)
re6 = ada.predict(X)
re7 = svc.predict(X)


D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [32]:
re1

array([85, 64, 93, ..., 98, 80, 91])

In [34]:
xx = X

In [35]:
re_1 = np.reshape(re1, (re1.shape[0],1))
re_2 = np.reshape(re2, (re2.shape[0],1))
re_3 = np.reshape(re3, (re3.shape[0],1))
re_4 = np.reshape(re4, (re4.shape[0],1))
re_5 = np.reshape(re5, (re5.shape[0],1))
re_6 = np.reshape(re6, (re6.shape[0],1))
re_7 = np.reshape(re7, (re7.shape[0],1))

xx = np.concatenate((xx, re_1), axis=1)
xx = np.concatenate((xx, re_2), axis=1)
xx = np.concatenate((xx, re_3), axis=1)
xx = np.concatenate((xx, re_4), axis=1)
xx = np.concatenate((xx, re_5), axis=1)
xx = np.concatenate((xx, re_6), axis=1)
xx = np.concatenate((xx, re_7), axis=1)

In [37]:
xx.shape

(10000, 17)

In [38]:
n_jobs = 2
n_iter = 10
cv = 5
seed=42
n_features=xx.shape[1]

estimator = XGBClassifier(nthreads=-1)
objective = 'binary:logistic'

# Parameter for XGBoost
params = {  
    "n_estimators": st.randint(3, 40),
    "max_depth": st.randint(3, 30),
    "learning_rate": st.uniform(0.05, 0.4),
    "colsample_bytree": st.beta(10, 1),
    "subsample": st.beta(10, 1),
    "gamma": st.uniform(0, 10),
    'objective': [objective],
    'scale_pos_weight': st.randint(0, 2),
    "min_child_weight": st.expon(0, 50),
    "seed": [seed],
}
xgb2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

estimator = LogisticRegression()
# Parameter for LogisticRegression
params = {
    "penalty": ['l2'],
    "C": [0.001, 0.01, 0.1, 1, 10],
    "tol": [1e-4, 1e-3, 1e-2, 1e-1],
    "solver": ['newton-cg', 'lbfgs', 'liblinear', 'sag'],
    "max_iter": st.randint(50, 100),
    'random_state': [seed],
} 
log2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

estimator = RandomForestClassifier()
# Parameter for RandomForestClassifier
params = {
    "max_depth": [3, None],
    "max_features": st.randint(1, n_features),
    "min_samples_split": st.randint(2, 10),
    "min_samples_leaf": st.randint(1, n_features),
    "bootstrap": [True, False],
    "criterion": ["gini", "entropy"],
    'random_state': [seed],
}
rnf2 = RandomizedSearchCV(estimator, params, cv=cv,n_jobs=n_jobs, n_iter=n_iter) 

In [39]:
vote_list = [('xgb2', xgb2), ('log2', log2), ('rnf2', rnf2)]
vote2 = VotingClassifier(estimators=vote_list, voting='soft')
vote2.fit(xx, y)

VotingClassifier(estimators=[('xgb2', RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,...obs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0))],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)

In [43]:
# vote2.feature_importances_

AttributeError: 'VotingClassifier' object has no attribute 'feature_importances_'

In [40]:
vote2.score(xx, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [45]:
# predict process
re1 = xgb.predict(X)
re2 = log.predict(X)
re3 = knn.predict(X)
re4 = rnf.predict(X)
re5 = ext.predict(X)
re6 = ada.predict(X)
re7 = svc.predict(X)

re_1 = np.reshape(re1, (re1.shape[0],1))
re_2 = np.reshape(re2, (re2.shape[0],1))
re_3 = np.reshape(re3, (re3.shape[0],1))
re_4 = np.reshape(re4, (re4.shape[0],1))
re_5 = np.reshape(re5, (re5.shape[0],1))
re_6 = np.reshape(re6, (re6.shape[0],1))
re_7 = np.reshape(re7, (re7.shape[0],1))

xx = np.concatenate((xx, re_1), axis=1)
xx = np.concatenate((xx, re_2), axis=1)
xx = np.concatenate((xx, re_3), axis=1)
xx = np.concatenate((xx, re_4), axis=1)
xx = np.concatenate((xx, re_5), axis=1)
xx = np.concatenate((xx, re_6), axis=1)
xx = np.concatenate((xx, re_7), axis=1)
print(xx,xx.shape)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[  6.46907649   4.25070317  -8.63694437 ...  85.          69.
   85.        ]
 [  6.48856404   9.37957037  10.32791736 ...  64.          69.
   64.        ]
 [  8.37392753 -10.14342267  -3.52753613 ...  93.          69.
   93.        ]
 ...
 [  7.86551596   6.19525794   4.773955   ...  98.          69.
   98.        ]
 [-10.41156442   1.40054826  -1.97349572 ...  80.          67.
   80.        ]
 [  7.40908901  -7.3908382   10.78350645 ...  91.          69.
   91.        ]] (10000, 31)


In [ ]:
y_final = vote2.predect()

In [ ]:
f1_score(y_val, y_final, average='macro')

In [ ]:
vote_list = [('xgb', xgb), ('log', log), ('knn', knn), ('rnf', rnf), ('ext', ext), ('ada', ada), ('svc', svc)]
vote = VotingClassifier(estimators=vote_list, voting='soft')
vote.fit(x_sm, y_sm)
y_pre = vote.predict(x_sm)
f1_score(y_sm, y_pre, average='binary')

D:\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)


In [56]:
vote.score(x, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9428171641791044

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [19]:
y_pre

array([85, 64, 93, ..., 98, 80, 91])

In [68]:
from sklearn.metrics import f1_score , precision_score , recall_score

In [63]:
f1_score(y, y_pre, average='binary')

0.0032520325203252032

In [73]:
precision_score(y, y_pre,pos_label=1, average='binary')

1.0

In [72]:
recall_score(y, y_pre,pos_label=1, average=None)

array([1.        , 0.00162866])

In [62]:
print(y,y_pre)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]] [0. 0. 0. ... 0. 0. 0.]


In [76]:
y_pre.sum()

1.0

In [57]:
joblib.dump(vote, 'vote.pkl') 


['vote.pkl']

In [25]:
vote2 = joblib.load('vote.pkl') 

In [26]:
vote2.score(X, y)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [27]:
vote2

VotingClassifier(estimators=[('xgb', RandomizedSearchCV(cv=5, error_score='raise',
          estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=nan, n_estimators=100,
 ...obs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0))],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)